//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class KanbanTFSEntities : DbContext
    {
        public KanbanTFSEntities()
            : base("name=KanbanTFSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectStatus> ProjectStatus1 { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<TFSWorkItem> TFSWorkItems { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<TfsConnection> TfsConnections { get; set; }
        public DbSet<TfsQuery> TfsQueries { get; set; }
    
        public virtual ObjectResult<GetProjectBoard_Result> GetProjectBoard(Nullable<int> projectID)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectBoard_Result>("GetProjectBoard", projectIDParameter);
        }
    }
}
