//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectStatus = new HashSet<ProjectStatus>();
            this.Users = new HashSet<User>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int ProjectID { get; set; }
        public string Name { get; set; }
        public int AdminID { get; set; }
    
         internal  ICollection<ProjectStatus> ProjectStatus { get; set; }
         internal  ICollection<User> Users { get; set; }
         internal  ICollection<Task> Tasks { get; set; }
    }
}
