//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStatus
    {
        public ProjectStatus()
        {
            this.TaskAssignments = new HashSet<TaskAssignment>();
        }
    
        public int ProjectStatusID { get; set; }
        public int ProjectID { get; set; }
        public string Name { get; set; }
    
         internal  Project Project { get; set; }
         internal  ICollection<TaskAssignment> TaskAssignments { get; set; }
    }
}
