//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.TaskAssignments = new HashSet<TaskAssignment>();
        }
    
        public int TaskID { get; set; }
        public Nullable<int> TFSTaskID { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
         internal  ICollection<TaskAssignment> TaskAssignments { get; set; }
         internal  Project Project { get; set; }
    }
}
