//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfsConnection
    {
        public TfsConnection()
        {
            this.TfsQueries = new HashSet<TfsQuery>();
        }
    
        public int TfsConfigID { get; set; }
        public string TfsUrl { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ProjectCollectionGuid { get; set; }
        public string Domain { get; set; }
    
         internal  ICollection<TfsQuery> TfsQueries { get; set; }
    }
}
