//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfsQuery
    {
        public int TfsQueryID { get; set; }
        public string QuerySrting { get; set; }
        public Nullable<int> TfsConfigID { get; set; }
    
         internal  TfsConnection TfsConnection { get; set; }
    }
}
