//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFSWorkItem
    {
        public int WorkItemID { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public string AssignedTo { get; set; }
        public string Attachement { get; set; }
        public bool Converted { get; set; }
    }
}
